version: '3.7'

services:
  nsqd:
    image: nsqio/nsq:v1.3.0
    command: /nsqd -broadcast-address=127.0.0.1 -lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - 4150:4150
      - 4151:4151

  nsqlookupd:
    image: nsqio/nsq:v1.3.0
    command: /nsqlookupd
    ports:
      - 4160:4160
      - 4161:4161
